# Generated by Django 4.2 on 2024-08-30 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth_data", "0001_initial"),
        ("post_messages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="auth_data.login",
                verbose_name="Владелец",
            ),
        ),
        migrations.DeleteModel(
            name="Login",
        ),
    ]
